# Generated by Django 4.1 on 2022-08-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entregable6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='dni',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
